class Constants:

	#### STATUSES ####

	STATUS_OK = "OK"

	# File statuses
	STATUS_FAIL_ENOENT = "ENOENT"
	STATUS_FAIL_ENOPERM = "ENOPERM"

	STATUS_FAIL_INSUFARGS = "INSUFARGS"

	STATUS_FAIL_TOOMANYITERS = "TOOMANYITERS"

	STATUS_FAIL_INCOMPMETA = "INCOMPTMETA"

	########

	MAX_SOCKET_QUEUE = 5
	BUFFER_SIZE = 10 * 1024 * 1024

	def __init__(self):
		pass


CONSTANTS = Constants()
